In [1]:
import torch 

In [3]:
t = torch.rand(10)

In [7]:
(t<0.5).to(torch.int)

tensor([0, 1, 1, 1, 0, 0, 1, 1, 0, 0], dtype=torch.int32)

In [19]:
loss = torch.nn.CrossEntropyLoss()

In [24]:
x = torch.rand(10,10,10)

In [25]:
y= x.view(-1)

In [27]:
y.shape

torch.Size([1000])

In [23]:
x = torch.rand(100,1)
y = torch.randn((100)).to(torch.long)
loss(x,y)

IndexError: Target -1 is out of bounds.

In [11]:
x.shape

torch.Size([100, 1])

In [71]:
x

tensor([[0.7875],
        [0.7864],
        [0.5873],
        [0.1354],
        [0.8382],
        [0.2324],
        [0.2216],
        [0.8692],
        [0.5961],
        [0.6434],
        [0.5000],
        [0.4099],
        [0.1977],
        [0.3442],
        [0.8187],
        [0.0890],
        [0.0117],
        [0.9570],
        [0.1479],
        [0.6236],
        [0.7740],
        [0.5858],
        [0.6415],
        [0.4834],
        [0.3195],
        [0.5597],
        [0.4318],
        [0.8500],
        [0.2325],
        [0.4478],
        [0.9778],
        [0.1683],
        [0.9471],
        [0.8378],
        [0.2504],
        [0.7679],
        [0.2694],
        [0.9961],
        [0.2250],
        [0.3569],
        [0.0589],
        [0.8541],
        [0.8685],
        [0.9747],
        [0.4356],
        [0.5249],
        [0.9659],
        [0.0836],
        [0.8825],
        [0.6678],
        [0.3828],
        [0.8257],
        [0.5058],
        [0.3379],
        [0.2079],
        [0

tensor(214.8417)

In [72]:
y

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0])